# Generated by Django 4.2.5 on 2024-01-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_property_details_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_details',
            name='PropertyType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
