# Generated by Django 4.2.5 on 2024-01-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_details',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
