# Generated by Django 4.2.5 on 2024-01-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_property_details_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_details',
            name='Status',
        ),
    ]
