# Generated by Django 4.2.5 on 2024-01-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_remove_property_details_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property_details',
        ),
    ]
