# Generated by Django 4.2.5 on 2024-01-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FrontEnd', '0004_delete_property_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenant', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Document_Proofs', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
