# Generated by Django 4.2.5 on 2024-01-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdb',
            name='ImageTenant',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
