# Generated by Django 4.2.5 on 2024-01-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0006_tenantdb_imagetenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdb',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
